project1/core/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]
# Show django were to grab media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project1/shop/urls.py
from django.urls import path
from . import views
#from .views import AllView

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    #path('items/', AllView.as_view(), name='all_items'),
    path('<slug:category_slug>/', views.item_list, name='item_list_by_category'),
    path('<int:id>/<slug:slug>/', views.item_detail, name='item_detail'),
]

project1/shop/models.py
from django.db import models

from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:item_list_by_category',
                       args=[self.slug])

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category,
                                related_name='items',
                                on_delete=models.CASCADE)
    name = models.CharField(max_length = 200, db_index=True)
    slug = models.SlugField(max_length = 200, db_index=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='gallery/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    #using decimal for prices to avoid rounding issue
    in_stock = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        #for queries involving id and slug
        

    def get_absolute_url(self):
        return reverse('shop:item_detail', 
                       args=[self.id, self.slug])

    def __str__(self):
        return self.name
    

project1/shop/views.py
from django.shortcuts import render, get_object_or_404
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#from django.views.generic import ListView
from .models import Category, Item

# Create your views here.

def item_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    items = Item.objects.filter(in_stock=True)
    # filtering by category
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)
        
    return render(request, 'shop/shop-items.html',
                 {'category': category, 'categories': categories, 'items': items})

def item_detail(request, id, slug):
    item = get_object_or_404(Item, id=id, slug=slug, in_stock=True)
    return render(request, 'shop/details.html', {'item': item})
    # the slug parameter is added to make seo-friendly urls

project1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Your cart:
            <a href="{% url "cart:cart_detail" %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
          {% else %}
            Your cart is empty.
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

project1/templates/shop/details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ item.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if item.image %}{{ item.image.url }}{% else %}
    {% static "img/default.png" %}{% endif %}">
    <h1>{{ item.name }}</h1>
    <h2>
      <a href="{{ item.category.get_absolute_url }}">
        {{ item.category }}
      </a>
    </h2>
    <p class="price">{{ item.price }} FCFA</p>
    {{ item.description|linebreaks }}
  </div>
{% endblock %}

project1/templates/shop/shop-items.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:item_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in items %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}
            {{ product.image.url }}
            {% else %}
            {% static "img/default.png" %}
            {% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        {{ product.price }} FCFA
      </div>
    {% endfor %}
  </div>
{% endblock %}